#Tarea Desafío 
#Guido Vega
services:

  #Hello Curiosity, dame las fotos
  uno:
     tty: true
     stdin_open: true
     build: 
       context: .
       dockerfile: Dockerfile
     volumes:
       - .:/home
     command: ./get-curious.py

  eth:
     tty: true
     stdin_open: true
     environment:
       PGUID: 1000
       PUID: 1000
       PYTHONWARNINGS: default
     build:
       context: .
       dockerfile: Dockerfile
     volumes:
       - .:/home
     command: ./eth.py


